// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2oOjd8FBxz-F3HiKMw-4D4wb65gNlXc',
    appId: '1:120787392573:web:82bb937265ac4faa577254',
    messagingSenderId: '120787392573',
    projectId: 'vegetavle-c5a2e',
    authDomain: 'vegetavle-c5a2e.firebaseapp.com',
    storageBucket: 'vegetavle-c5a2e.appspot.com',
    measurementId: 'G-E9BWH0ZEZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8h0rN3atGFKrsPl_OXZIV21diy4Pk0E',
    appId: '1:120787392573:android:abb0d3b687667f96577254',
    messagingSenderId: '120787392573',
    projectId: 'vegetavle-c5a2e',
    storageBucket: 'vegetavle-c5a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZ_JAJ5G_DQIH5yig1OHCma4FAPTJxHI',
    appId: '1:120787392573:ios:bb750dd1ccf21c33577254',
    messagingSenderId: '120787392573',
    projectId: 'vegetavle-c5a2e',
    storageBucket: 'vegetavle-c5a2e.appspot.com',
    iosClientId: '120787392573-07cp4m587llkandvgjqqd4si9lpg6oku.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZ_JAJ5G_DQIH5yig1OHCma4FAPTJxHI',
    appId: '1:120787392573:ios:bb750dd1ccf21c33577254',
    messagingSenderId: '120787392573',
    projectId: 'vegetavle-c5a2e',
    storageBucket: 'vegetavle-c5a2e.appspot.com',
    iosClientId: '120787392573-07cp4m587llkandvgjqqd4si9lpg6oku.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocy',
  );
}
